# Generated by Django 3.2.6 on 2021-10-05 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210921_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualización')),
            ],
            options={
                'verbose_name': 'categoriaProd',
                'verbose_name_plural': 'categoriasProd',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tienda', verbose_name='imagen')),
                ('price', models.FloatField(verbose_name='precio')),
                ('available', models.BooleanField(default=True, verbose_name='disponible')),
                ('content', models.TextField(verbose_name='contenido')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualización')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.categoryprod', verbose_name='categorias')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created'],
            },
        ),
    ]
